### ISSUE TITLE
Postgres Notify

### ISSUE THREAD

**Issue by avelino** [allisson/fastqueue#30]
From what I understand you are using "normal" tables to store the "queue" data.
Do you know (have you thought) about using the native Postgres queueing feature?

https://www.postgresql.org/docs/current/sql-notify.html

**Comment by allisson** [comment]
Hello @avelino,

I like the listen/notify feature from PostgreSQL, but this feature is primarily for notification when changes occur and I think the queue system needs something different to operate.

For fastqueue is essential to have the message stored in queues for later consumption. We need controls to expire and move messages (in the dead queue workflow) as well.
